version: 2
updates:
  # Update npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    ignore:
      - dependency-name: "eslint"
        versions: [">=9"]
      - dependency-name: "eslint-plugin-n"
        versions: [">=17"]
      - dependency-name: "eslint-plugin-promise"
        versions: [">=7"]

  # Update GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      actions:
        patterns:
          - "*"
