version: 2
updates:
  # Update npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      env:
        patterns:
          - "*jsdom*"
          - "*happy-dom*"
      all:
        patterns:
          - "*"

  # Update GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      actions:
        patterns:
          - "*"
