name: 📖 Documentation Suggestion
description: Suggestions on how we can improve the documentation.
title: '[📖]'
labels: [ 'COMP: docs', 'STATUS-1: needs triage' ]
body:
  - type: textarea
    id: description
    attributes:
      description: 'A clear and concise description of your suggestion to improve the docs.'
      label: Suggestion
    validations:
      required: true